# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "ubuntu-bionic-#{SecureRandom.hex(3)}"

  config.vm.network "public_network", ip: "192.168.1.211",bridge: "en0: Wi-Fi (Wireless)"

  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/authorized_keys"
  config.vm.provision "shell", inline: "sudo cp /tmp/authorized_keys /root/.ssh/authorized_keys"

  config.vm.provision "shell", path: "../init-script.sh"
end