apiVersion: v1
kind: ConfigMap
metadata:
  name: s3fs-config
data:
  S3_ENDPOINT: "http://192.168.2.18:4567"
  AWS_ACCESS_KEY_ID: "123"
  AWS_SECRET_ACCESS_KEY: password
  S3_BUCKET: bucket
  S3_EXTRAVARS: ",use_path_request_style"
  MOUNT_POINT: /mnt/data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-s3
  labels:
    app: nginx-s3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-s3
  template:
    metadata:
      labels:
        app: nginx-s3
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          resources:
            limits:
              cpu: 1
              memory: 512Mi
            requests:
              cpu: 1
              memory: 512Mi
          volumeMounts:
            - name: data
              mountPath: /usr/share/nginx/html
              mountPropagation: HostToContainer
        - name: s3f3
          image: internal-registry.ghostcloud.cn/library/f3fs:v1.85
          imagePullPolicy: Always
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          envFrom:
            - configMapRef:
                name: s3fs-config
          volumeMounts:
            - name: data
              mountPath: /mnt/data
              mountPropagation: Bidirectional
          resources:
            limits:
              cpu: 1
              memory: 512Mi
            requests:
              cpu: 1
              memory: 512Mi
      volumes:
        - name: data
          emptyDir: {}
      dnsPolicy: ClusterFirst
status: {}
