apiVersion: v1
kind: ConfigMap
metadata:
  name: s3fs-config
data:
  S3_ENDPOINT: "https://oss-cn-north-1.unicloudsrv.com"
  S3_ACCESS_KEY: "<16 chars access key>"
  S3_SECRET_KEY: "<32 chars secret key>"
  S3_BUCKET_NAME: "aidptest"
  S3_BUCKET_PATH: "/nginx"
  S3_EXTRAVARS: ",use_path_request_style"
  MOUNT_POINT: /mnt/data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: data
              mountPath: /usr/share/nginx/html
              mountPropagation: HostToContainer
        - name: s3f3-sidecar
          image: docker.io/fatalc/s3fs:v1.85
          imagePullPolicy: Always
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          envFrom:
            - configMapRef:
                name: s3fs-config
          volumeMounts:
            - name: data
              mountPath: /mnt/data
              mountPropagation: Bidirectional
      volumes:
        - name: data
          emptyDir: {}
      dnsPolicy: ClusterFirst
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
